# Generated by Django 4.0.8 on 2022-12-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='location',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
